name: devsecops

on:
  push:
    tags:        
      - v*.*.*
    #branches:
    #  - master
    # paths:
    #   - "src/**"
  workflow_call:

jobs:
  build-app:
    uses: codepraxis-io/github-actions/.github/workflows/app-build-workflow.yml@main
    with:
      build_dir: 'venv'
      docker_build_image: 'ghcr.io/codepraxis-io/ubuntu22.04:python3.10-build'
      #docker_image_tag_suffix: 'ubuntu22.04-python3.10'
    #secrets: inherit
    secrets: 
      destination_registry_username: ${{secrets.GHCR_USERNAME}}
      destination_registry_password: ${{secrets.GHCR_TOKEN}}
      cosign_private_key: ${{secrets.COSIGN_PRIVATE_KEY}}
      cosign_private_key_password: ${{secrets.COSIGN_PRIVATE_KEY_PASSWORD}}
      cosign_public_key: ${{secrets.COSIGN_PUBLIC_KEY}}

  # docker-build-scan-push:
  #   uses: codepraxis-io/github-actions/.github/workflows/app-docker-workflow.yml@main
  #   with:
  #     dockerfile_name: 'Dockerfile.distroless-multistage'
  #     docker_image_name: 'flask-bootstrap'
  #     docker_image_tag_suffix: 'distroless-multistage'
  #     verify_base_image_signature: 'false'
  #   #secrets: inherit
  #   secrets: 
  #     destination_registry_username: ${{secrets.GHCR_USERNAME}}
  #     destination_registry_password: ${{secrets.GHCR_TOKEN}}
  #     cosign_private_key: ${{secrets.COSIGN_PRIVATE_KEY}}
  #     cosign_private_key_password: ${{secrets.COSIGN_PRIVATE_KEY_PASSWORD}}
  #     cosign_public_key: ${{secrets.COSIGN_PUBLIC_KEY}}
