name: docker-build-scan-push

on:
  push:
    tags:        
      - v*.*.*
    #branches:
    #  - master
    # paths:
    #   - "src/**"
  workflow_call:

jobs:
  docker-build-scan-push:
    uses: codepraxis-io/github-actions/.github/workflows/docker-build-scan-push-workflow.yml@main
    with:
      dockerfile_name: 'Dockerfile.distroless-multistage'
      docker_image_name: 'flask-bootstrap'
      docker_image_tag_suffix: 'distroless-multistage' 
    secrets:
      destination_registry_username: ${{secrets.GHCR_USERNAME}}
      destination_registry_password: ${{secrets.GHCR_TOKEN}}
      cosign_private_key: ${{secrets.COSIGN_PRIVATE_KEY}}
      cosign_private_key_password: ${{secrets.COSIGN_PRIVATE_KEY_PASSWORD}}
      cosign_public_key: ${{secrets.COSIGN_PUBLIC_KEY}}
