name: ubuntu-22.04

on:
  push:
    tags:        
      - v*.*.*
    #branches:
    #  - master
    # paths:
    #   - "src/**"
  workflow_call:

jobs:
  build-app:
    uses: codepraxis-io/github-actions/.github/workflows/app-build-workflow.yml@main
    with:
      build_dir: 'venv'
      docker_build_image: 'ghcr.io/codepraxis-io/ubuntu22.04:python3.10-build'
    #secrets: inherit
    secrets: 
      destination_registry_username: ${{secrets.GHCR_USERNAME}}
      destination_registry_password: ${{secrets.GHCR_TOKEN}}
      cosign_private_key: ${{secrets.COSIGN_PRIVATE_KEY}}
      cosign_private_key_password: ${{secrets.COSIGN_PRIVATE_KEY_PASSWORD}}
      cosign_public_key: ${{secrets.COSIGN_PUBLIC_KEY}}

  docker-build-scan-push:
    uses: codepraxis-io/github-actions/.github/workflows/app-docker-workflow.yml@main
    needs: ['build-app']
    with:
      build_dir: 'venv'
      dockerfile_name: 'Dockerfile'
      docker_image_name: 'flask-bootstrap'
      docker_image_tag_suffix: 'ubuntu22.04-python3.10'
    #secrets: inherit
    secrets: 
      destination_registry_username: ${{secrets.GHCR_USERNAME}}
      destination_registry_password: ${{secrets.GHCR_TOKEN}}
      cosign_private_key: ${{secrets.COSIGN_PRIVATE_KEY}}
      cosign_private_key_password: ${{secrets.COSIGN_PRIVATE_KEY_PASSWORD}}
      cosign_public_key: ${{secrets.COSIGN_PUBLIC_KEY}}
